author: Ross Warren
title: peregrinescode
url: https://rosswarren.net
description: >- # this means to ignore newlines until "baseurl:"
  Ross Warren is physicist based at the University of Oxford. This
  website hosts a blog, publications, projects and a CV.
email: ross.warren@pm.me
twitter_username: _prwarren
github_username:  peregrinescode