author: Ross Warren
title: peregrinescode
url: https://rosswarren.net
description: >- # this means to ignore newlines until "baseurl:"
  Ross Warren is physicist based at the University of Oxford. This
  website hosts a blog, publications, projects and a CV.
email: helloworld@rosswarren.net
twitter_username: _rosswarren
github_username:  peregrinescode


plugins: ['jekyll/scholar']
scholar:
  sort_by: year, month
  order: descending
  style: _bibliography/mystyle.csl
  bibliography_template: bib